---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/logout":
    post:
      summary: User logout
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: successful login
        '401':
          description: invalid credentials
      
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
