---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users/tokens/sign_in":
    post:
      summary: User login
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: successful login
        '400':
          description: invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/users/tokens/revoke":
    post:
      summary: User logout
      tags:
      - Authentication
      parameters:
      - name: Authorization
        in: header
      responses:
        '204':
          description: successful logout
  "/users/tokens/sign_up":
    post:
      summary: User signup
      tags:
      - Authentication
      parameters: []
      responses:
        '201':
          description: successful signup
        '422':
          description: Record Invalid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                first_name:
                  type: string
                last_name:
                  type: string
                phone_number:
                  type: string
              required:
              - email
              - password
              - first_name
              - last_name
  "/api/v1/users/profile":
    get:
      summary: get profile
      tags:
      - Users APIs
      parameters:
      - name: Authorization
        in: header
      responses:
        '200':
          description: successful logout
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
