---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users/tokens/sign_in":
    post:
      summary: User login
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: successful login
        '400':
          description: invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/users/tokens/revoke":
    post:
      summary: User logout
      tags:
      - Authentication
      parameters:
      - name: Authorization
        in: header
      responses:
        '204':
          description: successful logout
  "/users/tokens/sign_up":
    post:
      summary: User signup
      tags:
      - Authentication
      parameters: []
      responses:
        '201':
          description: successful signup
        '422':
          description: Record Invalid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                first_name:
                  type: string
                last_name:
                  type: string
                phone_number:
                  type: string
              required:
              - email
              - password
              - first_name
              - last_name
  "/api/v1/users/profile":
    get:
      summary: get profile
      tags:
      - Users APIs
      parameters:
      - name: Authorization
        in: header
      responses:
        '200':
          description: successful logout
          content:
            application/json:
              examples:
                sample:
                  value:
                    id: 123
                    email: demo@example.com
                    first_name: Cuong
                    last_name: Nguyen
                    phone_number: 0355xxxyyy
  "/api/v1/users/confirm_email":
    post:
      summary: confirm success
      tags:
      - Authentication
      parameters:
      - name: Authorization
        in: header
      responses:
        '200':
          description: ok
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                confirmation_token:
                  type: string
              required:
              - confirmation_token
  "/api/v1/users/3":
    put:
      summary: Update current user profile
      tags:
      - Users APIs
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '200':
          description: user updated successfully
          content:
            application/json:
              examples:
                user profile updated:
                  value:
                    id: 1
                    email: john.doe@example.com
                    first_name: John
                    last_name: Doe
                    phone_number: 0355xxxyyy
                    avatar_url: https://bukmeup.com/rails/active_storage/blobs/.../avatar.jpg
                    cover_url: https://bukmeup.com/rails/active_storage/blobs/.../cover.jpg
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                  full_name:
                    type: string
                  phone_number:
                    type: string
                  avatar_url:
                    type: string
                    nullable: true
                  cover_url:
                    type: string
                    nullable: true
        '401':
          description: unauthorized
          content:
            application/json:
              examples:
                unauthorized:
                  value:
                    error: Unauthorized
              schema:
                type: object
                properties:
                  error:
                    type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: string
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
